apiVersion: v1
kind: Pod
metadata:
  name: demo-pod
  spec:
    replicas: 3
    selector:
      matchLabels:
        project: new-nginx
spec:
  containers:
    - name: new-nginx
      image: nginx
    - name: new-centos
      image: centos
      command: ["sh","-c","while : ; do curl http://localhost:80/; sleep 10; done"]