version: "3.5"
services:
  web:
    image: nginx:alpine
    networks:
      - my-network
    deploy:
      replicas: 10
      update_config:
        parallelism: 2
        delay: 10s
networks:
  my-network:
    driver: overlay


