version: "3.5"
services:
  newapp:
    image: training/whoami
    networks:
      - test-net
    ports:
      - 6000:6000
    deploy:
      replicas: 6
      update_config:
        parallelism: 2
        delay: 10s
      labels:
        app: new-app
networks:
  test-net:
    driver: overlay